import * as x509 from "@peculiar/x509"
import {Base64} from "js-base64"
import {yaml} from 'js-yaml'
import 'fs';

const crt="LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJakNDQWdxZ0F3SUJBZ0lRVHZvUmNaditiVFFnWk1TU044WFZUREFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGallT\n" +
"NTRZM0F1ZEdWMGNtRjBaUzVwYnpBZUZ3MHlNVEV3TURJeU1UQXlNalJhRncweQpOVEF6TURVeU1UQXlNalJhTUFBd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN1CnZGdWdzT0t\n" +
"3NXBEZW5RM0VrNVR1SFVDUzhHUnRTNC8vOHdPU2JaVEVjQk1uOTkyeHdJMXlXL1FlaDlkTnNZVG8KR2lOTzZDeHRaaHpnb1p0djErRVYxRUpKZUlKazd5UGlIaWRlcncrbndmb2R0a0VTU2lSTEVGVmtlT29TUE\n" +
"h0bgpvR0ptT0dIc2ppdlJXRWYrRjhlN0RRa0J0ajRlMWV2NEdENDM2UXJibElVWFdjekZIdUZUb3ZNRG8wSUdwNWd0CmFnTjBZdkZ0NGpOd1B0b0Q5WldPNHdHYTRLbWcxOWtaczBTbWREbFMvdEM1TFYwRGtjV\n" +
"GhUa1JMQmRDVWYyTmMKTnVhdGdWRzdXc2hETzMwQkovRUY4MWxoRHJJVi9vTEl2TTJDUHU0NmVPMVcxODhrUkhZTllORVpWYTlSMXNsVgp2UU9rMURFYm0vUkNwcUZhT0RjaEFnTUJBQUdqZkRCNk1CMEdBMVVk\n" +
"SlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyCkJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkc4eE1EbWIzalF2elhoak02ZmIKZldOVG9paDZNQ29HQTFVZEVRRUIvd1FnTUI2R0h\n" +
"ITndhV1ptWlRvdkwzaGpjQzUwWlhSeVlYUmxMbWx2TDJSbApiVzh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUZaVXh6UDFxWDh3Sm1JNk1XM2RtQ2dlNWMxbVhyMGVwQ09wCmhsdFFOSjdZS1VrZzE4WGhYV1\n" +
"Fob0JLcC9yemh5L2FwOGpmeWlyWktMRjJMVkFmaWhxVk1JMHE1TUhvSHVsRUwKaWZxZzM5TTRFYnBVeFlpSjU4VDAwekxHTXpZKzdYVmxsWGUwVHptWnl2dEFXSWVtUEhiRURKdnA3ZXJXbHhPYwpILzdzV1pmY\n" +
"W4zYUZPa1BJWTI2eFM2K2ZwK2FaalhiVTZ0UW51emQ5cVdlUzN6MnJyWVdnSmFYeW9RV3RBTENaCklNTVcyS28rVXBGdnZqeG9zK2lvVURJOW1uaHN3TGd3aVZrVGlJK2wrcmxwQWVLa2hlUVRqMjRKL3FaaXpU\n" +
"L2IKd2ZhSG5WK2p0T3VzU0tBWUp1cDZudGsxU255UXhCTG04ODJOZndrZXJXS0pFMUQ0Q0tRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEU3pDQ0F\n" +
"qT2dBd0lCQWdJUVhhblprSXVDRSt1TXowdzVPdlRPd1RBTkJna3Foa2lHOXcwQkFRc0ZBREFaCk1SY3dGUVlEVlFRREV3NTRZM0F1ZEdWMGNtRjBaUzVwYnpBZUZ3MHlNVEV3TURJeU1EVTVOVEJhRncweU5UQX\n" +
"oKTURVeU1EVTVOVEJhTUJ3eEdqQVlCZ05WQkFNVEVXTmhMbmhqY0M1MFpYUnlZWFJsTG1sdk1JSUJJakFOQmdrcQpoa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNMTU44Tmd5WjlhKzNLY1BIYTkzc\n" +
"XVMNzlvbTBPaW9QCm1RN01lVFllYU12REg5dDR6bEo2V1ZvS254WlVYcng4Y2NBeVdhMjZzR1FvTmtCZmtnYllEemVta0xod05iL2sKeENJRkYvSFVMZkowR0lKck5pY2Jrb21XSWZ4ekxDSTVsdjRndVFNb1g0\n" +
"MGNKMXl4cjJMVW1Qb3doWm15THRWdgpHSlFMRWRZckxnVTVjNmNsZmZWblhBRUZ3NFNsdUZYT1J4SVdwMDc5OGxCdXNaOUVJTk9YTW8zclE0a3NKdkpRCm1PY0xCQmJ1K2VmN2kxeTZLWThpWVFqR0toWW5JMW4\n" +
"1QWVNYXM2dGJkQmRkdExNai9rTURSdCtDa1kxWGF0MTIKeXcwZEg1dHZFU2pDNjIxRGxIRUhRdGd1YW5mUE5tVjJXTkVmY25pekphRURXOHQ0K3Z0ZGZ3SURBUUFCbzRHTApNSUdJTUE0R0ExVWREd0VCL3dRRU\n" +
"F3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlJ2Ck1UQTVtOTQwTDgxNFl6T24yMzFqVTZJb2VqQWZCZ05WSFNNRUdEQVdnQlJFVVlJbW9HMm5sa3lWSTI3WlhFNXQKYVU3VmJ6QWxCZ\n" +
"05WSFJFRUhqQWNoaHB6Y0dsbVptVTZMeTk0WTNBdWRHVjBjbUYwWlM1cGJ5OWpZVEFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQUs5NEU5UHBwbzNBQ2RlRlVZZmZvemRZdVBIN0Z2TW5TU2VHNlRxNjB5aHJT\n" +
"CjVoQkRzTVByaU11ZVVpM3hWYUFwdG1HMjFESjBaRE42RHZIZVptYStSVmFnOHhUOFhmYytvakRuZWNKUjhQTnIKeXNqeXhlMU55TUZaTUxyNXlBM0xQbm4xN0c5R09UbEtHUDdMMitOQjNTb2xGR1pBUHI3WS9\n" +
"TTkE0TksydUVtdgpLQXA3aEtkRmdOTlE3RjNhM1V1dExlYldrNnNVdTRCdFlYSWNqQllvV1FPRjRqTVVHTEVkazFPVUdUZnBGZFNsCjJiWnBvTmJhNGRtem9DTkxUc08vU3RENG1EQ3RtL3lXallQVUQwa0ZsU2\n" +
"NFa0c2VlpXTkd4ejhpTFUxZWtHbHAKajZIU2pJWE41R005OW9VOHNPWlBHbGw0S0x3UmxsWVdHRTVmOWNhWUNnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
const decoded = Base64.decode(crt)
const lines = decoded.split(/\r\n|\n/);
let buf = ""
for (let i = 0; i< lines.length; i++) {
    const line = lines[i]
    switch  (line) {
        case "-----BEGIN CERTIFICATE-----":
            // begin cert
            break;
        case "-----END CERTIFICATE-----":
            // end cert
            // console.log(Base64.decode(buf))
            const decoded = Base64.decode(buf)
            console.log('BUF')
            console.log(buf)
            console.log('DECODED');
            console.log(decoded)

            const cert = new x509.X509Certificate(decoded)
            buf = ""
            break
        default:
            buf = buf + line + '\n'
    }
}